# Generated by Django 5.2.1 on 2025-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('completed_status', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
